trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'Npm install'
  inputs:
    command: 'install'

- task: CmdLine@2
  displayName: 'Compile typescript'
  inputs:
    script: 'tsc'